#!/usr/bin/env bash
# shellcheck disable=SC2154

# This overrides the default k8s deploy action.

root_dir="$(dirname "${0}")/../../"
docker build \
  --build-arg branch="${branch}" \
  --build-arg environment="${environment}" \
  -f "${root_dir}/scripts/Dockerfile" \
  "${root_dir}"
