#!/usr/bin/env bash
# shellcheck disable=SC2154

# This overrides the default k8s deploy action.

set -x
set -e
set -u

while getopts b:c:e:ft opt; do
  case ${opt} in
    b)
      branch="${OPTARG}"
    ;;
    *)
      true
    ;;
  esac
done

eval "$(getconfig -s berklee-open -e "${branch}")"
root_dir="$(dirname "${0}")/../../"
docker build \
  --build-arg AMPLIFY_APP_ID="${AMPLIFY_APP_ID}" \
  --build-arg CONTENTFUL_DELIVERY_TOKEN="${CONTENTFUL_DELIVERY_TOKEN}" \
  --build-arg CONTENTFUL_PREVIEW_TOKEN="${CONTENTFUL_PREVIEW_TOKEN}" \
  --build-arg CONTENTFUL_SPACE_ID="${CONTENTFUL_SPACE_ID}" \
  --build-arg WEBHOOK="${WEBHOOK}" \
  --build-arg branch="${branch}" \
  --build-arg environment="${branch}" \
  -f "${root_dir}/scripts/Dockerfile" \
  "${root_dir}"
