#!/bin/bash
# shellcheck disable=SC1090,SC1091

set -x
set -e
set -u

declare -gx branch=dev

# Any option such as -c that isn't processed is here just to satisfy CI/CD
# stuff which passes some default arguments (like -c for cluster).
while getopts ":" opt; do
  case ${opt} in
    b)
      branch="${OPTARG}"
    ;;
    *)
      true
    ;;
  esac
done

if [ "${branch}" != 'dev' ] && [ "${branch}" != 'production' ]; then
  exit 0
fi

npm install

rm -rf amplify-backup
amplify pull -y --appId "${AMPLIFY_APP_ID}" --envName "${branch}"
amplify publish -y --invalidateCloudFront
